repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.15
    hooks:
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: 
          - --fix
          - --exclude=src/featclus/__init__.py  # Ruta al archivo que quieres excluir
      - id: ruff-format
        types_or: [python, pyi, jupyter]
